### ISSUE TITLE
Faulty regex terms in the data generation step

### ISSUE THREAD

**Issue by shepp-hub** [MGI-tech-bioinformatics/SARS-CoV-2_Multi-PCR_v1.0#1]
Hi,
In the first automatically-generated script (step0.GenerateData.sh), the sequencing files are selected through the following regular expression:
`ln -s /datasets/covid/VID/*1_1.fq.gz /datasets/covid/VID/result/VXXXXXX/01.Clean/Raw_VXXXXX_L0X_1_1_1.fq.gz`
This is problematic, since other sequencing files with identical suffixes, such as VXXXXX_L0X_71_71_1.fq.gz or VXXXXX_L0X_21_21_1.fq.gz, will also be included in such a statement.
I suggest using a safer regular expression, to avoid potential issues.

**Comment by meizhiying** [comment]
Hi,
  Thanks for your suggestion.
  In this situation, you can change the second column of the sample.list from '1_1' to 'VXXXXX_L0X_1_1', slide+lane+bc will be safer.

**Comment by MGI-tech-bioinformatics** [comment]
issue closed
